export const LOAD_APPLICATION_SUCCESS = "LOAD_APPLICATION_SUCCESS"
export const UPDATE_APPLICATION_SUCCESS = "UPDATE_APPLICATION_SUCCESS"

export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS"
export const UPDATE_PROJECT = "UPDATE_PROJECT"

export const LOAD_CONTACT_SUCCESS = "LOAD_CONTACT_SUCCESS"
export const UPDATE_CONTACT = "UPDATE_CONTACT"

export const LOAD_PEPITE_SUCCESS = "UPDATE_PEPITE_SUCCESS"
export const UPDATE_PEPITE = "UPDATE_PEPITE"

export const LOAD_CAREER_SUCCESS = "UPDATE_CAREER_SUCCESS"
export const UPDATE_CAREER = "UPDATE_CAREER"
