export const LOAD_APPLICATION_SUCCESS = "LOAD_APPLICATION_SUCCESS"
export const UPDATE_APPLICATION_SUCCESS = "UPDATE_APPLICATION_SUCCESS"

export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS"
export const UPDATE_PROJECT = "UPDATE_PROJECT"

export const LOAD_CONTACT_SUCCESS = "LOAD_CONTACT_SUCCESS"
export const UPDATE_CONTACT = "UPDATE_CONTACT"

export const LOAD_PEPITE_SUCCESS = "UPDATE_PEPITE_SUCCESS"
export const UPDATE_PEPITE = "UPDATE_PEPITE"

export const LOAD_CAREER_SUCCESS = "UPDATE_CAREER_SUCCESS"
export const UPDATE_CAREER = "UPDATE_CAREER"

export const LOAD_COMMITTEE_ANSWER_SUCCESS = "LOAD_COMMITTEE_ANSWER_SUCCESS"
export const UPDATE_COMMITTEE_ANSWER = "UPDATE_COMMITTEE_ANSWER"

export const LOAD_COMMITTEES_SUCCESS = "LOAD_COMMITTEES_SUCCESS"
export const CREATE_COMMITTEE_SUCCESS = "CREATE_COMMITTEE_SUCCESS"
export const UPDATE_COMMITTEE_SUCCESS = "UPDATE_COMMITTEE_SUCCESS"
export const DELETE_COMMITTEE_SUCCESS = "DELETE_COMMITTEE_SUCCESS"

export const LOAD_NEXT_COMMITTEE_SUCCESS = "LOAD_NEXT_COMMITTEE_SUCCESS"

export const LOAD_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE = "UPDATE_PROFILE"

export const UPDATE_ERRORS = "UPDATE_ERRORS"

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
