export const regions = [
  { name: 'Alsace - Champagne-Ardenne - Lorraine', establishments: [0, 1] },
  { name: 'Aquitaine - Limousin - Poitou-Charentes', establishments: [] },
  { name: 'Auvergne - Rhône-Alpes', establishments: [] },
  { name: 'Bourgogne - Franche-Comté', establishments: [] },
  { name: 'Bretagne', establishments: [2] },
  { name: 'Centre - Val de Loire', establishments: [] },
  { name: 'Corse', establishments: [] },
  { name: 'Île de France', establishments: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  { name: 'Languedoc - Roussillon - Midi-Pyrénées', establishments: [] },
  { name: 'Nord-Pas-de-Calais - Picardie', establishments: [24, 25] },
  { name: 'Normandie', establishments: [] },
  { name: 'Pays de la Loire', establishments: [] },
  { name: 'Provence-Alpes-Côte d\'Azur', establishments: [] },
  { name: 'Départements et régions d\'outre-mer', establishments: [] }
]


export const pepites = [
  'ETENA',
  'Champagne-Ardenne',
  'by PEEL',
  'ECA',
  'LPC',
  'PEEA',
  'BeeLYS',
  'oZer',
  'Bretagne',
  'Centre-Val de Loire',
  'Corse',
  'CréaJ IDF',
  '3EF',
  'heSam Entreprendre',
  'Paris Ouest Nord',
  'Paris Centre',
  'PEIPS',
  'PSL',
  'Languedoc-Roussillon',
  'ECRIN',
  'Lille Nord de France',
  'Picard',
  'Vallée de Seine',
  'CRÉER',
  'Aix-Marseille PACA-OUEST',
  'Cré@tude PACA-EST',
  'Antilles-Guyane',
  'P2ER'
]
export const establishments = [
  { name: 'établissements de l\'académie de Strasgbourg', pepite: 1 },
  { name: 'établissements de l\'académie de Reins', pepite: 2 },
  { name: 'établissements de l\'académie de Rennes', pepite: 8 },
  { name: 'Arts et Métiers ParisTech', pepite: 13 },
  { name: 'ESCP Europe', pepite: 13 },
  { name: 'Université Paris 13', pepite: 11 },
  { name: 'ENS de Paris', pepite: 17 },
  { name: 'Université Paris 8', pepite: 14 },
  { name: 'Université Paris 10', pepite: 14 },
  { name: 'IIM', pepite: 14 },
  { name: 'École de management Léonard de Vinci', pepite: 14 },
  { name: 'EDC Paris Business School', pepite: 14 },
  { name: 'ESILV', pepite: 14 },
  { name: 'Institut Catholique de Paris', pepite: 14 },
  { name: 'EPF École d\'ingenieur·e·s', pepite: 14 },
  { name: 'ISG International Business School', pepite: 14 },
  { name: 'IÉSEG School of Management', pepite: 14 },
  { name: 'Comue Université Paris-Est', pepite: 12 },
  { name: 'UPEC', pepite: 12 },
  { name: 'UPEM', pepite: 12 },
  { name: 'École des Ponts ParisTech', pepite: 12 },
  { name: 'ESIEE Paris', pepite: 12 },
  { name: 'École de l\'architecture de la ville et des territoires à Marne-la-Vallée', pepite: 12 },
  { name: 'École spéciale des travaux publics, du bâtiment et de l\'industrie', pepite: 12 },
  { name: 'établissements de l\'académie d\'Amiens', pepite: 21 },
  { name: 'établissements de l’académie de Lille', pepite: 20 }
]
