const pepites = [
  { _id: 1, name: 'ETENA', email: 'a.latour@unistra.fr' },
  { _id: 2, name: 'Champagne-Ardenne', email: 'pepitechampagneardenne@carinna.fr' },
  { _id: 3, name: 'by PEEL', email: 'peel@univ-lorraine.fr' },
  { _id: 4, name: 'ECA', email: 'eca@cuea.fr' },
  { _id: 5, name: 'LPC', email: 'pepitelpc@groupes.renater.fr' },
  { _id: 6, name: 'PEEA', email: 'pepite.auvergne@sigma-clermont.fr' },
  { _id: 7, name: 'BeeLYS', email: 'beelys@fpul-lyon.org' },
  { _id: 8, name: 'oZer', email: 'entrepreneuriat@univ-grenoble-alpes.fr' },
  { _id: 9, name: 'Bretagne', email: 'pepite-bretagne@u-bretagneloire.fr' },
  { _id: 10, name: 'Centre-Val de Loire', email: 'contact@pepite-centre.fr' },
  { _id: 11, name: 'Corse', email: 'pagni@univ-corse.fr' },
  { _id: 12, name: 'CréaJ IDF', email: 'gestion.pepite@univ-paris13.fr' },
  { _id: 13, name: '3EF', email: 'pepite3ef@univ-paris-est.fr' },
  { _id: 14, name: 'heSam Entreprendre', email: 'dossier.pepite@hesam.eu' },
  { _id: 15, name: 'Paris Ouest Nord', email: 'contact@pepite-pon.fr' },
  { _id: 16, name: 'Paris Centre', email: 'entrepreneur@sorbonne-universites.fr' },
  { _id: 17, name: 'PEIPS', email: 'pepite@universite-paris-saclay.fr' },
  { _id: 18, name: 'PSL', email: 'psl-pepite@univ-psl.fr' },
  { _id: 19, name: 'Languedoc-Roussillon', email: 'contact@pepite-lr.fr' },
  { _id: 20, name: 'ECRIN', email: 'ecrin@univ-toulouse.fr' },
  { _id: 21, name: 'Lille Nord de France', email: 'envoi@tonpepite.com' },
  { _id: 22, name: 'Picardie', email: 'pepite.picardie@gmail.com' },
  { _id: 23, name: 'Vallée de Seine', email: 'pepite-valleedeseine@normandie-univ.fr' },
  { _id: 24, name: 'CRÉER', email: 'pepite.creer@u-bretagneloire.fr' },
  { _id: 25, name: 'Aix-Marseille PACA-OUEST', email: 'suio-pepite-paca-ouest@univ-amu.fr' },
  { _id: 26, name: 'Cré@tude PACA-EST', email: 'pepitepacaest@unice.fr' },
  { _id: 27, name: 'Antilles-Guyane', email: 'pepiteag@univ-ag.fr' },
  { _id: 28, name: 'P2ER', email: 'pepite.p2er@univ-reunion.fr' },
  { _id: 29, name: 'Bourgone Franche-Comté', email: 'coordination@pepite-bfc.fr'}
]

module.exports = pepites
