export const regions = [
  { name: 'Alsace - Champagne-Ardenne - Lorraine', establishments: [0] },
  { name: 'Bretagne', establishments: [1] },
  { name: 'Île de France', establishments: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33] },
  { name: 'Nord-Pas-de-Calais - Picardie', establishments: [34] }
]


export const pepites = [
  'ETENA',
  'Champagne-Ardenne',
  'by PEEL',
  'ECA',
  'LPC',
  'PEEA',
  'BeeLYS',
  'oZer',
  'Bretagne',
  'Centre-Val de Loire',
  'Corse',
  'CréaJ IDF',
  '3EF',
  'heSam Entreprendre',
  'Paris Ouest Nord',
  'Paris Centre',
  'PEIPS',
  'PSL',
  'Languedoc-Roussillon',
  'ECRIN',
  'Lille Nord de France',
  'Picardie',
  'Vallée de Seine',
  'CRÉER',
  'Aix-Marseille PACA-OUEST',
  'Cré@tude PACA-EST',
  'Antilles-Guyane',
  'P2ER'
]
export const establishments = [
  { name: 'établissements de l\'académie de Strasgbourg', pepite: 0 },
  { name: 'établissements de l\'académie de Rennes', pepite: 8 },
  { name: 'Arts et Métiers ParisTech', pepite: 13 },
  { name: 'École nationale vétérinaire d'Alfort', pepite: 13 },
  { name: 'École nationale supérieure d'architecture de Paris-Belleville', pepite: 13 },
  { name: 'École des Ingénieurs de la Ville de Paris', pepite: 13 },
  { name: 'École nationale des sciences géographiques', pepite: 13 },
  { name: 'École nationale supérieure d'architecture de Paris-Malaquais', pepite: 13 },
  { name: 'ESCP Europe', pepite: 13 },
  { name: 'Centre de Formation des Journalistes', pepite: 13 },
  { name: 'Centre Michel Serres', pepite: 13 },
  { name: 'CNAM', pepite: 13 },
  { name: 'École du Louvre', pepite: 13 },
  { name: 'ENA', pepite: 13 },
  { name: 'ENSAPLV', pepite: 13 },
  { name: 'ENSCI', pepite: 13 },
  { name: 'ESCP Europe', pepite: 13 },
  { name: 'IFM', pepite: 13 },
  { name: 'INHA', pepite: 13 },
  { name: 'Institut national du patrimoine', pepite: 13 },
  { name: 'Université Paris 1', pepite: 13 },
  { name: 'INED', pepite: 13 },
  { name: 'Université Paris 8', pepite: 14 },
  { name: 'Université Paris Nanterre', pepite: 14 },
  { name: 'IIM', pepite: 14 },
  { name: 'EMLV', pepite: 14 },
  { name: 'EDC Paris Business School', pepite: 14 },
  { name: 'ESILV', pepite: 14 },
  { name: 'Institut Catholique de Paris', pepite: 14 },
  { name: 'EPF École d\'ingenieur·e·s', pepite: 14 },
  { name: 'ISG International Business School', pepite: 14 },
  { name: 'IÉSEG School of Management', pepite: 14 },
  { name: 'Comue Université Paris-Est', pepite: 12 },
  { name: 'UPEC', pepite: 12 },
  { name: 'UPEM', pepite: 12 },
  { name: 'École des Ponts ParisTech', pepite: 12 },
  { name: 'ESIEE Paris', pepite: 12 },
  { name: 'École de l\'architecture de la ville et des territoires à Marne-la-Vallée', pepite: 12 },
  { name: 'École spéciale des travaux publics, du bâtiment et de l\'industrie', pepite: 12 },
  { name: 'établissements de l\'académie d\'Amiens', pepite: 21 },

]
