export const regions = [
  { name: 'Alsace - Champagne-Ardenne - Lorraine', establishments: [0, 86] },
  { name: 'Bretagne', establishments: [1] },
  { name: 'Île de France', establishments: [2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82] },
  { name: 'Nord-Pas-de-Calais - Picardie', establishments: [34, 84] },
  { name: 'Aquitaine', establishments: [11] },
  { name: 'Normandie', establishments: [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 61,] },
  { name: 'Pays de Loire', establishments: [83] },
  { name: 'Auvergne - Rhône-Alpes', establishments: [85] },
]

export const pepites = [
  'ETENA',
  'Champagne-Ardenne',
  'by PEEL',
  'ECA',
  'LPC',
  'PEEA',
  'BeeLYS',
  'oZer',
  'Bretagne',
  'Centre-Val de Loire',
  'Corse',
  'CréaJ IDF',
  '3EF',
  'heSam Entreprendre',
  'Paris Ouest Nord',
  'Paris Centre',
  'PEIPS',
  'PSL',
  'Languedoc-Roussillon',
  'ECRIN',
  'Lille Nord de France',
  'Picardie',
  'Vallée de Seine',
  'CRÉER',
  'Aix-Marseille PACA-OUEST',
  'Cré@tude PACA-EST',
  'Antilles-Guyane',
  'P2ER'
]
export const establishments = [
  { name: 'établissements de l\'académie de Strasgbourg', pepite: 0 },
  { name: 'établissements de l\'académie de Rennes', pepite: 8 },
  { name: 'Arts et Métiers ParisTech', pepite: 13 },
  { name: 'ESCP Europe', pepite: 13 },
  { name: 'Centre de Formation des Journalistes', pepite: 13 },
  { name: 'Centre Michel Serres', pepite: 13 },
  { name: 'CNAM', pepite: 13 },
  { name: 'École du Louvre', pepite: 13 },
  { name: 'ENA', pepite: 13 },
  { name: 'ENSAPLV', pepite: 13 },
  { name: 'ENSCI', pepite: 13 },
  { name: 'établissements de l\'académie de Bordeaux', pepite: 3 },
  { name: 'IFM', pepite: 13 },
  { name: 'INHA', pepite: 13 },
  { name: 'Institut national du patrimoine', pepite: 13 },
  { name: 'Université Paris 1', pepite: 13 },
  { name: 'INED', pepite: 13 },
  { name: 'Université Paris 8', pepite: 14 },
  { name: 'Université Paris Nanterre', pepite: 14 },
  { name: 'IIM', pepite: 14 },
  { name: 'EMLV', pepite: 14 },
  { name: 'EDC Paris Business School', pepite: 14 },
  { name: 'ESILV', pepite: 14 },
  { name: 'Institut Catholique de Paris', pepite: 14 },
  { name: 'EPF École d\'ingenieur·e·s', pepite: 14 },
  { name: 'ISG International Business School', pepite: 14 },
  { name: 'IÉSEG School of Management', pepite: 14 },
  { name: 'Comue Université Paris-Est', pepite: 12 },
  { name: 'UPEC', pepite: 12 },
  { name: 'UPEM', pepite: 12 },
  { name: 'École des Ponts ParisTech', pepite: 12 },
  { name: 'ESIEE Paris', pepite: 12 },
  { name: 'École de l\'architecture de la ville et des territoires à Marne-la-Vallée', pepite: 12 },
  { name: 'École spéciale des travaux publics, du bâtiment et de l\'industrie', pepite: 12 },
  { name: 'établissements de l\'académie d\'Amiens', pepite: 21 },
  { name: 'École nationale vétérinaire d\'Alfort', pepite: 12 },
  { name: 'École nationale supérieure d\'architecture de Paris-Belleville', pepite: 12 },
  { name: 'École des Ingénieurs de la Ville de Paris', pepite: 12 },
  { name: 'École nationale des sciences géographiques', pepite: 12 },
  { name: 'École nationale supérieure d\'architecture de Paris-Malaquais', pepite: 12 },
  { name: 'Cesi', pepite: 22 },
  { name: 'CNAM', pepite: 22 },
  { name: 'EBI - École de Biologie', pepite: 22 },
  { name: 'ENSP - École Supérieure de Paysage de Versailles', pepite: 22 },
  { name: 'EISTI - Traitement de l\'information', pepite: 22 },
  { name: 'ENSEA', pepite: 22 },
  { name: 'EPMI', pepite: 22 },
  { name: 'ESSEC', pepite: 22 },
  { name: 'ILEPS - Métiers du sport', pepite: 22 },
  { name: 'ISTOM', pepite: 22 },
  { name: 'ITESCIA', pepite: 22 },
  { name: 'Université Cergy Pontoise', pepite: 22 },
  { name: 'École de Management de Normandie', pepite: 22 },
  { name: 'ENSA Normanide - Ecole d\'architecture', pepite: 22 },
  { name: 'ENSI Caen', pepite: 22 },
  { name: 'Esadhar', pepite: 22 },
  { name: 'Esigelec', pepite: 22 },
  { name: 'INSA Rouen Normandie', pepite: 22 },
  { name: 'Neoma', pepite: 22 },
  { name: 'Université Caen Normandie', pepite: 22 },
  { name: 'Université Le Havre Normandie', pepite: 22 },
  { name: 'Université Rouen Normandie', pepite: 22 },
  { name: 'Chimie ParisTech', pepite: 17 },
  { name: 'Collège de France', pepite: 17 },
  { name: 'Conservatoire national supérieur de musique et de danse de Paris', pepite: 17 },
  { name: 'École des hautes études en sciences sociales', pepite: 17 },
  { name: 'École française d\'Extrême-Orient', pepite: 17 },
  { name: 'École nationale des chartes', pepite: 17 },
  { name: 'École nationale supérieure des Arts Décoratifs', pepite: 17 },
  { name: 'École nationale supérieure des beaux-arts', pepite: 17 },
  { name: 'École normale supérieure', pepite: 17 },
  { name: 'École Pratique des Hautes Études', pepite: 17 },
  { name: 'ESPCI', pepite: 17 },
  { name: 'Institut Curie', pepite: 17 },
  { name: 'La Fémis', pepite: 17 },
  { name: 'Lycée Henri-IV', pepite: 17 },
  { name: 'MINES ParisTech', pepite: 17 },
  { name: 'Observatoire de Paris', pepite: 17 },
  { name: 'Université Paris-Dauphine', pepite: 17 },
  { name: 'Institut Pasteur', pepite: 17 },
  { name: 'Epita', pepite: 17 },
  { name: 'Epitech', pepite: 17 },
  { name: 'ETNA', pepite: 17 },
  { name: 'établissements de l\'académie de Nantes', pepite: 23 },
  { name: 'établissements de l\'académie de Lille', pepite: 20 },
  { name: 'établissements de l\'académie de Lyon', pepite: 6 },
  { name: 'établissements de l’académie de Nancy-Metz', pepite: 2 },
]
