export const diplomas = [
  'BTS, DMA, DCESF',
  'CPGE',
  'DUT',
  'DEUG',
  'Licence professionnelle',
  'Licence (avant LMD)',
  'Licence LMD',
  'Bachelor',
  'Maîtrise',
  'Master LMD',
  'Mastère spécialisé, magistère',
  'Diplôme d\'ingénieur',
  'Diplôme d\'écolé de commerce ou de gestion',
  'Diplôme de santé',
  'Diplôme paramédical ou social',
  'Diplôme d\'école d\'art ou d’arts appliqués',
  'Diplôme d\'école d\'architecture',
  'Doctorat',
  'Diplôme univeristaire ou d\'établissement'
]
