const establishments = [{ _id: 1, name: 'établissements de l\'académie de Strasgbourg', region: 1, pepite: 1 },
{ _id: 2, name: 'établissements de l\'académie de Rennes', region: 3, pepite: 5 },
{ _id: 3, name: 'Arts et Métiers ParisTech', region: 4, pepite: 13 },
{ _id: 4, name: 'ESCP Europe', region: 4, pepite: 13 },
{ _id: 5, name: 'Centre de Formation des Journalistes', region: 4, pepite: 13 },
{ _id: 6, name: 'Centre Michel Serres', region: 4, pepite: 13 },
{ _id: 7, name: 'CNAM', region: 4, pepite: 13 },
{ _id: 8, name: 'école du Louvre', region: 4, pepite: 13 },
{ _id: 9, name: 'ENA', region: 4, pepite: 13 },
{ _id: 10, name: 'ENSAPLV', region: 4, pepite: 13 },
{ _id: 11, name: 'ENSCI', region: 4, pepite: 13 },
{ _id: 12, name: 'établissements de l\'académie de Bordeaux', region: 6, pepite: 2 },
{ _id: 13, name: 'IFM', region: 4, pepite: 13 },
{ _id: 14, name: 'INHA', region: 4, pepite: 13 },
{ _id: 15, name: 'Institut national du patrimoine', region: 4, pepite: 13 },
{ _id: 16, name: 'Université Paris 1', region: 4, pepite: 13 },
{ _id: 17, name: 'INED', region: 4, pepite: 13 },
{ _id: 18, name: 'Université Paris 8', region: 4, pepite: 14 },
{ _id: 19, name: 'Université Paris Nanterre', region: 4, pepite: 14 },
{ _id: 20, name: 'IIM', region: 4, pepite: 14 },
{ _id: 21, name: 'EMLV', region: 4, pepite: 14 },
{ _id: 22, name: 'EDC Paris Business School', region: 4, pepite: 14 },
{ _id: 23, name: 'ESILV', region: 4, pepite: 14 },
{ _id: 24, name: 'Institut Catholique de Paris', region: 4, pepite: 14 },
{ _id: 25, name: 'EPF École d\'ingenieur·e·s', region: 4, pepite: 14 },
{ _id: 26, name: 'ISG International Business School', region: 4, pepite: 14 },
{ _id: 27, name: 'IÉSEG School of Management', region: 4, pepite: 14 },
{ _id: 28, name: 'Comue Université Paris-Est', region: 4, pepite: 12 },
{ _id: 29, name: 'UPEC', region: 4, pepite: 12 },
{ _id: 30, name: 'UPEM', region: 4, pepite: 12 },
{ _id: 31, name: 'École des Ponts ParisTech', region: 4, pepite: 12 },
{ _id: 32, name: 'ESIEE Paris', region: 4, pepite: 12 },
{ _id: 33, name: 'École de l\'architecture de la ville et des territoires à Marne-la-Vallée', region: 4, pepite: 12 },
{ _id: 34, name: 'École spéciale des travaux publics, du bâtiment et de l\'industrie', region: 4, pepite: 12 },
{ _id: 35, name: 'établissements de l\'académie d\'Amiens', region: 5, pepite: 25 },
{ _id: 36, name: 'École nationale vétérinaire d\'Alfort', region: 4, pepite: 12 },
{ _id: 37, name: 'École nationale supérieure d\'architecture de Paris-Belleville', region: 4, pepite: 12 },
{ _id: 38, name: 'École des Ingénieurs de la Ville de Paris', region: 4, pepite: 12 },
{ _id: 39, name: 'École nationale des sciences géographiques', region: 4, pepite: 12 },
{ _id: 40, name: 'École nationale supérieure d\'architecture de Paris-Malaquais', region: 4, pepite: 12 },
{ _id: 41, name: 'Cesi', region: 4, pepite: 4 },
{ _id: 42, name: 'CNAM', region: 4, pepite: 4 },
{ _id: 43, name: 'EBI - École de Biologie', region: 4, pepite: 4 },
{ _id: 44, name: 'ENSP - École Supérieure de Paysage de Versailles', region: 4, pepite: 4 },
{ _id: 45, name: 'EISTI - Traitement de l\'information', region: 4, pepite: 4 },
{ _id: 46, name: 'ENSEA', region: 4, pepite: 4 },
{ _id: 47, name: 'EPMI', region: 4, pepite: 4 },
{ _id: 48, name: 'ESSEC', region: 4, pepite: 4 },
{ _id: 49, name: 'ILEPS - Métiers du sport', region: 4, pepite: 4 },
{ _id: 50, name: 'ISTOM', region: 4, pepite: 4 },
{ _id: 51, name: 'ITESCIA', region: 4, pepite: 4 },
{ _id: 52, name: 'Université Cergy Pontoise', region: 4, pepite: 4 },
{ _id: 53, name: 'École de Management de Normandie', region: 11, pepite: 4 },
{ _id: 54, name: 'ENSA Normanide - Ecole d\'architecture', region: 11, pepite: 4 },
{ _id: 55, name: 'ENSI Caen', region: 11, pepite: 4 },
{ _id: 56, name: 'Esadhar', region: 11, pepite: 4 },
{ _id: 57, name: 'Esigelec', region: 11, pepite: 4 },
{ _id: 58, name: 'INSA Rouen Normandie', region: 11, pepite: 4 },
{ _id: 59, name: 'Neoma', region: 11, pepite: 4 },
{ _id: 60, name: 'Université Caen Normandie', region: 11, pepite: 4 },
{ _id: 61, name: 'Université Le Havre Normandie', region: 11, pepite: 4 },
{ _id: 62, name: 'Université Rouen Normandie', region: 11, pepite: 4 },
{ _id: 63, name: 'Chimie ParisTech', region: 4, pepite: 17 },
{ _id: 64, name: 'Collège de France', region: 4, pepite: 17 },
{ _id: 65, name: 'Conservatoire national supérieur de musique et de danse de Paris', region: 4, pepite: 17 },
{ _id: 66, name: 'École des hautes études en sciences sociales', region: 4, pepite: 17 },
{ _id: 67, name: 'École française d\'Extrême-Orient', region: 4, pepite: 17 },
{ _id: 68, name: 'École nationale des chartes', region: 4, pepite: 17 },
{ _id: 69, name: 'École nationale supérieure des Arts Décoratifs', region: 4, pepite: 17 },
{ _id: 70, name: 'École nationale supérieure des beaux-arts', region: 4, pepite: 17 },
{ _id: 71, name: 'École normale supérieure', region: 4, pepite: 17 },
{ _id: 72, name: 'École Pratique des Hautes Études', region: 4, pepite: 17 },
{ _id: 73, name: 'ESPCI', region: 4, pepite: 17 },
{ _id: 74, name: 'Institut Curie', region: 4, pepite: 17 },
{ _id: 75, name: 'La Fémis', region: 4, pepite: 17 },
{ _id: 76, name: 'Lycée Henri-IV', region: 4, pepite: 17 },
{ _id: 77, name: 'MINES ParisTech', region: 4, pepite: 17 },
{ _id: 78, name: 'Observatoire de Paris', region: 4, pepite: 17 },
{ _id: 79, name: 'Université Paris-Dauphine', region: 4, pepite: 17 },
{ _id: 80, name: 'Institut Pasteur', region: 4, pepite: 17 },
{ _id: 81, name: 'Epita', region: 4, pepite: 17 },
{ _id: 82, name: 'Epitech', region: 4, pepite: 17 },
{ _id: 83, name: 'ETNA', region: 4, pepite: 17 },
{ _id: 84, name: 'établissements de l\'académie de Nantes', region: 12, pepite: 24 },
{ _id: 85, name: 'établissements de l\'académie de Lille', region: 5, pepite: 23 },
{ _id: 86, name: 'établissements de l\'académie de Lyon', region: 2, pepite: 28 },
{ _id: 87, name: 'établissements de l’académie de Nancy-Metz', region: 1, pepite: 21 },
{ _id: 88, name: 'établissements de l’académie de Reims', region: 1, pepite: 7 },
{ _id: 89, name: 'établissements des académies de Limoges et Poitiers', region: 6, pepite: 20 },
{ _id: 90, name: 'établissements de l\'académie de Clermont-Ferrand', region: 2, pepite: 3 },
{ _id: 91, name: 'établissements de l\'académie de Grenoble', region: 2, pepite: 29 },
{ _id: 92, name: 'établissements des académies de Besançon et de Dijon', region: 7, pepite: 9 },
{ _id: 93, name: 'établissements de l’académie d’Orléans-Tours', region: 8, pepite: 6 },
{ _id: 94, name: 'établissements de l’académie de Corse', region: 9, pepite: 8 },
{ _id: 95, name: 'établissements de l’académie de Montpellier', region: 10, pepite: 19 },
{ _id: 96, name: 'établissements de l’académie de Toulouse', region: 10, pepite: 22 },
{ _id: 97, name: 'établissements de l’académie d’Aix-Marseille', region: 13, pepite: 26 },
{ _id: 98, name: 'établissements de l’académie de Nice', region: 13, pepite: 27 },
{ _id: 99, name: 'établissements des académies des Antilles et de Guyane', region: 14, pepite: 10 },
{ _id: 100, name: 'établissements des académies de la Réunion et de Mayote', region: 14, pepite: 18 },
{ _id: 101, name: 'Université Paris 13', region: 4, pepite: 11 },
{ _id: 102, name: 'Université Paris 3', region: 4, pepite: 11 },
{ _id: 103, name: 'Université Paris 5', region: 4, pepite: 11 },
{ _id: 104, name: 'Université Paris 7', region: 4, pepite: 11 },
{ _id: 105, name: 'IEP de Paris', region: 4, pepite: 11 },
{ _id: 106, name: 'IPG', region: 4, pepite: 11 },
{ _id: 107, name: 'INALCO', region: 4, pepite: 11 },
{ _id: 108, name: 'EHESP', region: 4, pepite: 11 },
{ _id: 109, name: 'ISC Paris', region: 4, pepite: 11 },
{ _id: 110, name: 'Novancia', region: 4, pepite: 11 },
{ _id: 111, name: 'PSB', region: 4, pepite: 11 },
{ _id: 112, name: 'Ecole de Commerce du Sport Business', region: 4, pepite: 11 },
{ _id: 113, name: 'EFREI', region: 4, pepite: 11 },
{ _id: 114, name: 'Sorbonne Universités', region: 4, pepite: 15 },
{ _id: 115, name: 'Université Paris 4', region: 4, pepite: 15 },
{ _id: 116, name: 'Université Paris 6', region: 4, pepite: 15 },
{ _id: 117, name: 'MNHN', region: 4, pepite: 15 },
{ _id: 118, name: 'UTC', region: 4, pepite: 15 },
{ _id: 119, name: 'INSEAD', region: 4, pepite: 15 },
{ _id: 120, name: 'PSPBB', region: 4, pepite: 15 },
{ _id: 121, name: 'Université Paris 2', region: 4, pepite: 15 },
{ _id: 122, name: 'ENM', region: 4, pepite: 15 },
{ _id: 123, name: 'INHA', region: 4, pepite: 15 },
{ _id: 124, name: 'Université Paris-Saclay', region: 4, pepite: 16 },
{ _id: 125, name: 'Université Paris 11', region: 4, pepite: 16 },
{ _id: 126, name: 'Université Versailles-Saint-Quentin-en-Yvelines', region: 4, pepite: 16 },
{ _id: 127, name: 'AgroParisTech', region: 4, pepite: 16 },
{ _id: 128, name: 'CentraleSupélec', region: 4, pepite: 16 },
{ _id: 129, name: 'HEC Paris', region: 4, pepite: 16 },
{ _id: 130, name: 'École polytechnique', region: 4, pepite: 16 },
{ _id: 131, name: 'ENS de Cachan', region: 4, pepite: 16 },
{ _id: 132, name: 'ENSTA ParisTech', region: 4, pepite: 16 },
{ _id: 133, name: 'ENSAE', region: 4, pepite: 16 },
{ _id: 134, name: 'Institut Mines-Télécom', region: 4, pepite: 16 },
{ _id: 135, name: 'Institut d’Optique Graduate School (IOGS)', region: 4, pepite: 16 },
{ _id: 136, name: 'Université d’Evry Val d’Essonne (UEVE)', region: 4, pepite: 16 },
{ _id: 137, name: 'Télécom Sud-Paris', region: 4, pepite: 16 },
{ _id: 138, name: 'Télécom Ecole de Mangement', region: 4, pepite: 16 },
{ _id: 139, name: 'ESTACA', region: 4, pepite: 16 },
{ _id: 140, name: 'Sup Career', region: 4, pepite: 15 },
{ _id: 141, name: 'Université de la Rochelle', region: 6, pepite: 2 },
]

module.exports = establishments
